apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-apod-deployment
  labels:
    app: web-apod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-apod
  template:
    metadata:
      labels:
        app: web-apod
    spec:
      containers:
      - name: web-apod-nginx
        image: eu.gcr.io/orbiter-279306/27ddbbc171be93d6e35ff76eb52e239c79b5f958-orgiter-web-apod
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
