apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: slack-api-java
        image: slack-api-image
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
