name: Deploy Orbiter Slack Server to Heroku

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy to Heroku
      run: ORBITER=$GITHUB_WORKSPACE $GITHUB_WORKSPACE/slack/server/ci/deploy.sh
