name: Deploy Orbiter Web APOD to Heroku

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
    - name: Build and deploy to Heroku
      env:
        ORBITER=$GITHUB_WORKSPACE
        DOCKER_REGISTRY_USERNAME=${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD=${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        HEROKU_API_TOKEN=${{ secrets.HEROKU_API_TOKEN }}
      run: $GITHUB_WORKSPACE/web/apod/ci/deploy.sh
