name: Deploy Orbiter Web APOD to GKE

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      GCLOUD_GCR_ACCOUNT: ${{ secrets.GCLOUD_GCR_ACCOUNT }}
      GCLOUD_GCR_KEY: ${{ secrets.GCLOUD_GCR_KEY }}
      GITOPS_REPO_ACCESS_KEY: ${{ secrets.GITOPS_REPO_ACCESS_KEY }}
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Init GCR
      run: TMP_GCR_FILE="$(mktemp)"; echo "$GCLOUD_GCR_KEY" > "$TMP_GCR_FILE"; echo "::set-env name=GCLOUD_GCR_KEY_FILE::$TMP_GCR_FILE";

    - uses: borales/actions-yarn@v2.0.0
    - name: Build app
      run: ORBITER=$GITHUB_WORKSPACE $GITHUB_WORKSPACE/web/apod/ci/build.sh

    - name: Build Manifest
      run: ORBITER=$GITHUB_WORKSPACE $GITHUB_WORKSPACE/ci/manifest.sh $GITHUB_WORKSPACE/web/apod web-apod.yaml

    - name: Release gitops
      run: ORBITER=$GITHUB_WORKSPACE $GITHUB_WORKSPACE/ci/push-gitops.sh
