name: Orbiter GKE cluster

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    env:
      TF_VAR_linux_admin_username: ${{ secrets.TF_VAR_linux_admin_username }}
      TF_VAR_linux_admin_password: ${{ secrets.TF_VAR_linux_admin_password }}
      TF_VAR_gcp_credentials: ${{ secrets.TF_VAR_gcp_credentials }}
      GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_BACKEND_CREDENTIALS }}
    name: Terraform cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: cd $GITHUB_WORKSPACE/infra/tf && terraform init

    - name: Terraform Plan
      run: cd $GITHUB_WORKSPACE/infra/tf && terraform plan

    - name: Terraform Apply
      run: cd $GITHUB_WORKSPACE/infra/tf && terraform apply -auto-approve
