name: Orbiter GKE cluster

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    env:
      TF_VAR_linux_admin_username: ${{ secrets.TF_VAR_linux_admin_username }}
      TF_VAR_linux_admin_password: ${{ secrets.TF_VAR_linux_admin_password }}
      TF_VAR_gcp_credentials: ${{ secrets.TF_VAR_gcp_credentials }}
      GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_BACKEND_CREDENTIALS }}
      GCLOUD_GKE_ACCOUNT: ${{ secrets.GCLOUD_GKE_ACCOUNT }}
      GCLOUD_GKE_KEY: ${{ secrets.GCLOUD_GKE_KEY }}
    name: Terraform cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.26

    - name: Terraform Init
      run: cd $GITHUB_WORKSPACE/infra/tf && terraform init

    - name: Create GKE keys
      run: TMP_GKE_FILE="$(mktemp)"; echo "$GCLOUD_GKE_KEY" > "$TMP_GKE_FILE"; echo "::set-env name=GCLOUD_GKE_KEY_FILE::$TMP_GKE_FILE";

    - name: Provision kubectl
      run: $GITHUB_WORKSPACE/ci/init-gke.sh orbiter-gke-clustes europe-west2-c orbiter-279306

    - name: Terraform Plan
      run: cd $GITHUB_WORKSPACE/infra/tf && terraform plan

    - name: Terraform Apply
      run: cd $GITHUB_WORKSPACE/infra/tf && terraform apply -auto-approve
